### ISSUE TITLE
Not working on madison 2. Any clue?

### ISSUE THREAD

**Issue by CyberPK** [DanielMuller/koken-plugin-photoswipe#34] opened 2016-11-24 00:45 UTC
Hi, I got it working on another theme but I can't get it working on madison 2 theme.
I've installed, enabled and deleted system cache but appear the standard lightbox. Any idea?

Thanks

*** edit ***
I've tracked the problem to list layout of the theme madison2 that is not using pillar. I've modified the plugin to return always false in usingPillar() function and photoswipe started working. If I navigate to other albums through the menu links, the lightbox appear again instead of photoswipe. If I refresh the page photoswipe works again. Any idea?

**Comment by DanielMuller** [comment] 2016-12-07 03:07
I guess Madison2 uses some kind of Javascript to refresh the pages, and this doesn't trigger the plugin (which acts only on HTML rendering). Refreshing the whole page will generate a new complete HTML which triggers the plugin.
On Javascript based themes, the plugin is really not working well, as it was intended primarily for Axis1.
I will try to reproduce the issue as soon as possible and see if there is something that can be done for Madison2

**Comment by CyberPK** [comment] 2016-12-12 02:16
Thank you!
Remember to set the list layout from the theme settings otherwise the issue won't appear with the default theme.

**Comment by DanielMuller** [comment] 2016-12-13 14:11
Sorry, but I can't debug this. I don't own a copy of Madison2

**Comment by CyberPK** [comment] 2016-12-14 13:51
Can I share it for the purpose of debugging the issue? If yes where can I send it?

**Comment by DanielMuller** [comment] 2016-12-14 15:05
Send it here: github@daniel.ctrlaltdel.ch

**Comment by CyberPK** [comment] 2016-12-15 04:56
I've sent the theme to you, and I've just figured out how to get it working.

**Comment by DanielMuller** [comment] 2016-12-19 08:26
Fixed by #35

**Closed** 2016-12-19 08:26 UTC
